---
title: 10 异步编程
date: 2020-08-25
categories:
    - 前端
tags:
	- ES6
---

async 与 await 

<!-- more -->

## 1. ES6 异步编程概述
JavaScript引擎是基于单线程（Single-threaded）事件循环的概念构建的，同一时刻只允许一个代码块在执行。JavaScript引擎同一时刻只能执行一个代码块，所以需要跟踪即将运行的代码，那些代码被放在一个**任务队列（job queue）**中，每当一段代码准备执行时，都会被添加到任务队列。每当JavaScript引擎中的一段代码结束执行，**事件循环（eventloop）**会执行队列中的下一个任务，它是JavaScript引擎中的一段程序，**负责监控代码执行并管理任务队列**。请记住，队列中的任务会从第一个一直执行到最后一个。为了在实现循环中实现异步编程，JavaScript 提供了如下异步编程模型:
1. 响应用户操作的时间
2. 回调函数
3. Promise
4. async/awit 定义的协程

### 1.1 事件
用户点击按钮或按下键盘上的按键会触发类似onclick这样的事件，它会向任务队列添加一个新任务来响应用户的操作。直到事件触发时才执行事件处理程序。

事件模型适用于处理简单的交互，但不适合组合复杂的异步逻辑。

### 1.2 回调函数
回调模式与事件模型类似，异步代码都会在未来的某个时间点执行，二者的区别是回调模式中被调用的函数是作为参数传入的。与事件相比回调模式比事件模型更灵活，通过回调模式链接多个调用更容易，但是很容易就陷入所谓的"回调地狱"中。

同事件一样，回调函数无法组合复杂的组合逻辑，例如，并行执行两个异步操作，当两个操作都结束时通知你；或者同时进行两个异步操作，只取优先完成的操作结果。

### 1.3 Promise
Promise相当于异步操作结果的占位符，类似于其他语言中类似Future和Deferred，用于表示操作的未来结果。Promise 具有生命周期:
1. 先是处于进行中（pending）的状态，此时操作尚未完成
2. 操作结束后，Promise可能会进入到以下两个状态中的其中一个：
    - Fulfilled　Promise异步操作成功完成
    - Rejected　由于程序错误或一些其他原因，Promise异步操作未能成功完成

内部属性 `[[PromiseState]]` 被用来表示Promise的3种状态："pending"、"fulfilled"及"rejected。基于成功或失败的状态，Promise 可以像事件和回调函数一样指定稍后执行的代码，可以链式地编写 Promise。接下来我们会详细介绍 Promise 提供的异步编程接口。需要说明的是 Promise 不暴露 `[[PromiseState]]` 属性，我们无法获取此属性值，但是 JavaScript 提供了其他方法让我们捕获 Promise 状态的变化，接下来我们会详细介绍。

### 1.4 协程
async/awit 定义的协程组合了生成器和 Promise，实现了以同步方式编写异步代码，要想明白其实现机制，我们需要按次序理解一下问题:
1. 如何使用生成器实现一个异步任务执行器
2. 如何让异步任务函数返回一个 Promise(表示未来操作的结果)
3. 如何让 Promise 与第一步定义的异步任务执行器结合，更好的将异步代码同步化。

在同步代码中，代码按照执行次序一行行执行，因为是同步，我们总是可以得到上一步执行的结果。在协程中，我们通过一个表示未来操作执行结果的 Promise 对象来得到上一行代码的执行结果(假设是异步操作)，让异步代码同步化。

## 2. Promise 
前面我们已经说过了，Promise 表示一个异步操作的结果，通过捕获 Promise 状态的变化我们可以获取异步操作的结果，基于结果我们可以定义接下来的操作。为此 Promise 提供了如下方法:
1. then()
2. catch()

### 2.1 Promise 定义的方法
promise.then(fulfilled_function, reject_function):
- 作用: 定义 Promise 状态改变时(异步操作完成后)，执行的操作
- 参数: 两个参数都是可选的
    - fulfilled_function: 
        - 当Promise的状态变为fulfilled时要调用的函数
        - 异步操作的返回值会传递给此函数
    - reject_function:
        - Promise的状态变为rejected时要调用的函数
        - 所有与失败状态相关的附加数据都会传递给这个拒绝函数
- 说明:
    - 如果一个对象实现了上述的then()方法，那这个对象我们称之为thenable对象
    - 分离的 fulfilled_function，reject_function 可以确切提供异步操作成功还是失败的处理语义，如果使用事件，在遇到错误时不会主动触发；如果使用回调函数，则必须要记得每次都检查错误参数
    - **如果不给Promise添加拒绝处理程序，那所有失败就自动被忽略了，所以一定要添加拒绝处理程序**
    - 每次调用then()方法或catch()方法都会创建一个新任务，当Promise 表示的异步任务执行完成时。这些任务最终都会被加入到一个为Promise量身定制的独立队列中，即便一个Promise处于已处理状态，在这之后添加到任务队列中的处理程序仍将执行
    - 如果执行器内部抛出一个错误，则Promise的拒绝处理程序就会被调用，每个执行器中都隐含一个try-catch块，所以错误会被捕获并传入拒绝处理程序

promise.catch(reject_function):
- 作用: 相当于只传入拒绝处理程序的then()方法
- 说明: **catch 提供了用于捕获异步操作错误的确切语义**

```js
// readFile 的实现参见 创建未完成的Promise 中示例
let promise = readFile("test.txt");

promise.then(function(contents){
    console.log(contents);
}, function(err){
    onsole.log(err.message);
})

promise.catch(function(err){
    onsole.log(err.message);
})
```

### 2.2 捕获已拒绝 Promise 的钩子
关Promise的其中一个最具争议的问题是，如果在没有拒绝处理程序的情况下拒绝一个Promise，那么不会提示失败信息，这是JavaScript语言中唯一一处没有强制报错的地方。Promise的特性决定了很难检测一个Promise是否被处理过，为此 Node.js 和 浏览器提供了捕获已拒绝 Promise 的钩子，虽然它们还不是 ES6 的标准。

当Promise 被拒绝时，浏览器会在 window 对象上触发两个事件:
1. unhandledrejection　在一个事件循环中，当Promise被拒绝，并且没有提供拒绝处理程序时被调用
2. rejectionhandled　在一个事件循环后，当Promise被拒绝，并且没有提供拒绝处理程序时被调用

这两个事件的事件处理程序会接受一个有以下属性的事件对象作为参数:
1. type: 事件名称（"unhandledrejection"或"rejectionhandled"）
2. promise: 被拒绝的Promise对象
3. reason: 来自Promise的拒绝值

### 2.3 创建未完成的Promise
所谓创建未完成的Promise，就是如何用 Promise 包装一个异步任务。这里的等价含义是如何将回调函数转换为Promise。

用Promise构造函数可以创建新的 Promise，其只接受一个参数：包含初始化Promise代码的执行器（executor）函数。执行器接受两个参数，分别是
1. resolve()函数，执行器成功完成时调用resolve()函数，resolve 函数接收的参数将被 Promise 传递给 fulfilled_function
2. reject()函数，执行器失败时则调用reject()函数，reject 函数接收的参数将被 Promise 传递给 reject_function

下面这个示例是在 Node.js 中用 Promise 实现的Promise 版 readFile()函数：

```js
// NodeJs 示例
let fs = require("fs");

function readFile(filename){
    return new Promise(function(resolve, reject){
        fs.readFile(filename, {"encoding": "utf8"}, function(err, contents){
            // 检查错误
            if (err){
                reject(err);
                return;
            }

            // 执行成功
            resolve(contents);
        });
    })
}

let promise = readFile("test.txt");

promise.then(function(contents){
    console.log(contents);
}, function(err){
    onsole.log(err.message);
})

```

当上面的 readFile()方法被调用时:
1. 执行器会立刻执行，fs.readFile 异步读取文件的函数会立即执行
2. 然后执行后续的 promise.then
3. 在执行器中，无论是调用resolve()还是reject()，都会向任务队列中添加一个任务来解决这个Promise(更新 Promise 状态)。类似于 setTimeout()或setInterval()函数向任务队列中添加一个新任务，并明确指定将**任务延后执行**
4. 当异步文件读取完成时，会调用resolve()/reject()触发一个异步操作，传入then()和catch()方法的函数会被添加到任务队列中并异步执行

因此整个代码的执行过程为
1. 当前事件循环: 
    1. 执行执行器
    2. 执行promise.then
2. 读文件完成所在的事件循环:
    - 调用 resolve()，想任务队列添加解决 Promise 的任务
3. 下一个事件循环:
    - 执行解决 Promise 的任务，真正调用 resolve() 将定义在 then()方法中的函数到任务队列
4. 下一事件循环:
    - 执行then()方法的函数

之所以**调用resolve()还是reject()，都会向任务队列中添加一个任务来解决这个Promise**，是为了保证 resolve()/reject() 的执行总是在 promise.then 方法之后执行，即使执行器执行的不是异步代码也是如此。这样才能保证完成处理程序和拒绝处理程序总是在执行器完成后被添加到任务队列的末尾。

### 2.4 创建已完成的 Promise
创建已处理的Promise表示你想用Promise来表示一个已知值，相对于编排一个只是简单地给resolve()函数传值的任务，更好的办法是使用如下方法:
1. Promise.resolve
2. Promise.reject

Promise.resolve(value)
- 作用: 接受一个参数并返回一个完成态的Promise
- 说明: 不会有任务编排的过程，而且需要向Promise添加一至多个完成处理程序来获取值

Promise.reject()
- 作用: 创建已拒绝的 Promise

Promise.resolve()和Promise.reject()都有如下特点:
1. 传入一个Promise，那么这个Promise会被直接返回
2. 都可以接受非Promise的Thenable对象作为参数，此时这些方法会创建一个新的Promise，并在then()函数中被调用

在下面这个示例中:
2. Promise.resolve()调用的是thenable.then()
3. 由于 then()方法内部调用了resolve(42)，因此thenable 被转换为一个已完成的 Promise p1，如果调用 reject(43) 则返回一个已拒绝的 Promise，当然也可以执行异步函数，根据异步函数结果调用 resolve 或者 reject
3. p1从Thenable对象接受传入的值（也就是42），p1的完成处理程序的形参value将被赋值 42

```js
let thenable = {
    then: function(resolve, reject) {
        resolve(42);
    }
}

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
    console.log(value);
})
```

有了Promise.resolve()方法和Promise.reject()方法，我们可以更轻松地处理非Promise的Thenable对象。

至此，看起来好像Promise只是将回调函数和setTimeout()函数结合起来，并在此基础上做了一些改进。但 Promise 实现的功能不仅如此。

### 2.5 Promise 提供的链式调用
每次调用 then() 或 catch() 方法时实际上创建并返回了另一个Promise，这样我们可以以链式调用的方式，串联起一连串异步操作，在这个链式调用中:
1. 只有前一个 Promise 完成或者失败后，才会触发下一个 Promise
2. 处于链式调用后端的拒绝处理程序，可以处理它前面所有 Promise 发生的异常，包括完成处理程序和拒绝处理程序。所以务必在Promise链的末尾留有一个拒绝处理程序以确保能够正确处理所有可能发生的错误
3. 如果在完成处理程序和拒绝处理程序中的返回值，可以沿着链式调用链继续传递
4. 完成和拒绝处理程序中返回了一个新的 Promise，相当于在调用链中插入了一个新的 Promise，这个新的 Promise 的完成状态决定了后面调用链的执行

```js
let p1 = new Promise(function(resole, reject) {
    throw new Error("Expose P1");
})

p1.catch(function(err) {
    console.log(err.message);
    throw new Error("Boom");
// 1. Promise 的链式调用
// 2. 链式 Promise 后面的调用可以感知到链中其他Promise的错误。
}).catch(function(err) {
    console.log(err.message);
})

let p2 = Promise.resolve(42);
p2.then(function(value) {
    // 3.完成处理程序的返回值可以在调用链上传递
    return value + 1;
}).then(function(value) {
    console.log(value); // 43
})

let pp1 = Promise.resolve(42);
let pp2 = Promise.resolve(43);

let pp3 = pp1.then(function(value) {
    console.log(value);
    // 4. 完成程序中返回的 Promise 相当于在调用链中插入这个 Promise
    // 5. pp1 then 返回的 pp3 是一个新的 Promise
    return pp2
});

console.log(pp3 === pp2);
```

### 2.6 Promise 提供的任务组合
前面我们看到的都是单个Promise响应，而如果想通过监听多个Promise来决定下一步的操作，则可以使用 ES6 提供的Promise.all() 和 Promise.race()两个方法


Promise.all(promise_iter):
- 参数: 含有多个受监视Promise的可迭代对象
- 作用: 返回一个 promise
    - 只有 promise_iter 中**所有 Promise**都被完成后返回的Promise才会被完成
    - promise_iter 中只要有一个 Promise 被拒绝，那么返回的Promise不会等所有Promise完成而立即被拒绝

```js
let p1 = new Promise(function(resole, reject) {
    setTimeout(function() {
            console.log("p1");
            resole(41);
        }, 200)
        // return resole(41);
})
console.log("p2")
let p2 = Promise.resolve(42);
let p3 = Promise.resolve(43);

let p4 = Promise.all([p1, p2, p3])
p4.then(function(value) {
    console.log(value); // [41, 42, 43]
}).catch(function(value){
    // 拒绝处理程序只接受一个值
    console.log(Array.isArray(value)); // false
})
```
在上面的示例中:
1. Promise.all()方法创建Promise p4
2. 传入p4完成处理程序的结果是一个包含每个Promise 完成处理程序返回值的（42、43和44）的数组，这些值与它们在 all 中传入的顺序一致
3. 如果 p1,p2,p3 任何一个失败，比如 p2 失败，p4 会立即失败，不会等 p1,p3 执行完成。p4 的拒绝处理程序总是接收一个值，来自被拒绝的 Promise

Promise.race(promise_iter):
- 参数: 含有多个受监视Promise的可迭代对象
- 作用: 返回一个 promise，传给Promise.race()方法的Promise会进行竞选，以决出哪一个先被解决，
    - 如果先解决的是已完成Promise，则返回已完成Promise
    - 如果先解决的是已拒绝Promise，则返回已拒绝Promise
- 应用:
    - 给某个异步请求设置超时时间

```js
let p1 = new Promise(function(resole, reject) {
        setTimeout(function() {
                console.log("p1输出");
                resole(41);
            }, 200)
            // return resole(41);
    })
let p2 = Promise.reject(42);
let p3 = Promise.resolve(43);

let p4 = Promise.race([p1, p2, p3])
p4.then(function(value) {
    console.log(value);
}).catch(function(value) {
    console.log("失败: ${value}")
})
```

在上面这段程序中:
1. 由于p2已处于被拒绝状态，因而当Promise.race()方法被调用时p4也被拒绝了
2. p4 不会等待 p1,p3 完成，所以打印的顺序是"失败:43 => p1 输出"

## 3. JavaScript 异步编程
前面我们说了，要搞清楚 awit/async 提供的异步编程机制，需要明白以下三个问题:
1. 如何使用生成器实现一个异步任务执行器
2. 如何让异步任务函数返回一个 Promise(表示未来操作的结果)
3. 如何让 Promise 与第一步定义的异步任务执行器结合，更好的将异步代码同步化

接下来我们就来一一解决这三个问题。

### 3.1 异步任务执行器
首先，生成器可以返回值也可以接收值，这就是在用户程序可独立调度的执行单元，又被称为"协程"，我们可以自己编写一个调度器来调度生成器的执行，示例代码像下面这样:

```js
// 异步任务执行器
function run(taskDef) {
    // 1. 调用生成器函数返回一个迭代器，并初始化
    let task = taskDef();
    let result = task.next();

    // 2. 不断迭代迭代器的调度程序
    function step() {
        if (!result.done) {
            value = result.value;
            // 3. 如果迭代返回的是一个函数，表示是一个异步任务
            if (typeof value === "function") {
                value(function(content, err) {
                    if (err) {
                        result = task.throw(err);
                        step();
                    } else {
                        result = task.next(content);
                        step();
                    }
                })
            }
            result = task.next(value);
            step();
        }
    }
    step();
}

let fs = require("fs");
// 定义一个可用于任务执行的函数
function reedFile(filename) {
    return function(callback) {
        fs.readFile(filename, callback);
    }
}

// 执行一个任务
run(function*() {
    let contents = yield readFile("example.txt");
    console.log(contentss)
})
```

在上面这个异步任务调度器中:
1. 原本以回调函数执行的异步任务，被包装成了一个接受参数和回调函数的嵌套函数
2. 异步任务的回调函数，被调度器设置成，根据异步任务结果，驱动调度器执行的函数

但是这个实现有一些明显的问题:
1. 首先，定义用于执行的函数，其返回值是一个接受回调函数的函数，很难理解，这句话本身也是如此
2. 无法区分用作任务执行器回调函数的返回值和一个不是回调函数的返回值

但是如果用 Promise 来表示每个异步操作的返回值，我们就可以大大简化调度器。这就引出来我们第二个问题，如何让异步任务函数返回一个 Promise。

### 3.2 让异步任务返回 Promise
这个问题的解决方案我们在讲解创建未完成的 Promise 就解决了:
```js
let fs = require("fs");

function readFile(filename){
    return new Promise(resolve, reject){
        fs.readFile(filename, {"encoding": "utf8"}, function(err, contents){
            // 检查错误
            if (err){
                reject(err);
                return;
            }

            // 执行成功
            resolve(contents);
        });
    }
}
```

最后我们来看如何把 Promise 和异步调度器结合起来。

### 3.3 结合 Promise 和异步调度器
```js
function run(taskDef) {
    // 1. 调用生成器函数返回一个迭代器，并初始化
    let task = taskDef();
    let result = task.next();

    // 2. 不断迭代迭代器的调度程序
    function step() {
        if (!result.done) {
            // 3. 总是将迭代器的返回值包装成一个 Promise 对象
            promise = Promise.resolve(result.value);
            
            // 4. 添加处理程序，提取Promise的值并将其传回迭代器
            promise.then(function(content){
                result = task.next(content);
                step();
            }).catch(function(err){
                result = task.throw(err);
                step();
            })
        }
    }
    step();
}
```

在这个版本的代码中:
1. Promise 完全表示出了它的语义，一个异步操作的未来的结果，代码非常清晰
2. 调用Promise.resolve()是为了防止函数不返回Promise，也就是说，用yield调用同步或异步方法都可以正常运行，永远不需要检查返回值是否为Promise。
3. 添加完成处理程序提取Promise的值并将其传回迭代器
4. 拒绝处理程序将所有拒绝结果存储到一个错误对象中，然后通过task.throw()方法将错误对象传回迭代器
5. 唯一需要关注的是像readFile()这样的异步函数，需要被转换成一个返回 Promise 对象的函数


## 4. async
ES2017 引入了 async/await 关键字，其内部原理就是我们刚刚所说的 Promise + 生成器函数。awit/async 其基本思想是用async标记的函数代替生成器，用await代替yield来调用函数，就像这样:
```js
// 1. async 修饰的函数总是返回一个 Promise 对象
async function f(){

}
console.log(f()); // Promise

// 2. 使用示例
(async function() {
    let contents = awit readFile("example.txt");
    console.log(contentss)
})
```
在上面的示例中:
1. async表示该函数以异步模式运行，函数的返回值总是被包装成一个 Promise 对象
2. await关键字表示调用readFile("config.json")的函数应该返回一个 Promise
2. 如果 await 后面不是一个 Promise 对象，JavaScript 会自动将其包装成一个 Promise 对象
3. 类似 run 的异步任务调度器，由 JavaScript 引擎提供
4. 如同 run 实现，如果Promise被拒绝则await应该抛出错误，否则通过Promise来返回值

最后的结果是，你可以按照同步方式编写异步代码。